[build]
command = "npx next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/api/public/*"
to = "/api/public/:splat"

  [redirects.rate_limit]
  window_limit = 20
  window_size = 60
  aggregate_by = ["ip", "domain"]
